// <auto-generated />
namespace IdentityCustom.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addintable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addintable));
        
        string IMigrationMetadata.Id
        {
            get { return "202004171413079_Addintable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
